#/***************************************************************************************
#* Copyright (c) 2021-2026 Beijing Institute of Open Source Chip (BOSC)
#* Copyright (c) 2020-2026 Institute of Computing Technology, Chinese Academy of Sciences (ICT，CAS)
#* 
#* YuQuan is licensed under Mulan PSL v2.
#* You can use this software according to the terms and conditions of the Mulan PSL v2.
#* You may obtain a copy of Mulan PSL v2 at:
#*          http://license.coscl.org.cn/MulanPSL2
#*
#* THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
#* EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
#* MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
#*   
#* See the Mulan PSL v2 for more details.
#***************************************************************************************/
.DEFAULT_GOAL := all

.PHONY: all vivado_prj vitis_prj clean

# =====================================================
# Tools
# =====================================================
VIVADO ?= vivado
XSCT   ?= xsct

# Number of parallel jobs used by Vivado runs.
JOBS ?= 8

# =====================================================
# Directories and artifacts
# =====================================================
ROOT_DIR := $(abspath $(dir $(lastword $(MAKEFILE_LIST))))

SRC_DIR         ?= $(ROOT_DIR)/srcs
VIVADO_SRC_DIR  ?= $(SRC_DIR)/vivado_srcs
VITIS_SRC_DIR   ?= $(SRC_DIR)/vitis_srcs
BUILD_DIR       ?= $(ROOT_DIR)/build
VIVADO_PRJ_DIR  ?= $(BUILD_DIR)/vivado_prj
VITIS_PRJ_DIR   ?= $(BUILD_DIR)/vitis_prj

XSA ?= $(BUILD_DIR)/fpga_top.xsa
BIT ?= $(BUILD_DIR)/fpga_top.bit
ELF ?= $(BUILD_DIR)/top.elf
VIVADO_STAMP := $(VIVADO_PRJ_DIR)/.build_complete

# =====================================================
# Logs
# =====================================================
LOG_DIR ?= $(ROOT_DIR)/logs

# =====================================================
# TCL scripts
# =====================================================
VIVADO_TCL ?= $(ROOT_DIR)/scripts/vivado_prj.tcl
VITIS_TCL  ?= $(ROOT_DIR)/scripts/vitis_prj.tcl
RUN_TCL    ?= $(ROOT_DIR)/scripts/run_vitis.tcl

# Recursively collect source files so make can rebuild stale artifacts.
rwildcard = $(foreach entry,$(wildcard $1*),$(call rwildcard,$(entry)/,$2) $(filter $(subst *,%,$2),$(entry)))
VIVADO_SRCS := $(foreach pattern,*.v *.sv *.svh *.xdc *.bd *.bda *.xci,$(call rwildcard,$(VIVADO_SRC_DIR)/,$(pattern)))
VITIS_SRCS  := $(foreach pattern,*.c *.h *.S *.s,$(call rwildcard,$(VITIS_SRC_DIR)/,$(pattern)))

# =====================================================
# Build targets
# =====================================================
all: vivado_prj vitis_prj

vivado_prj: $(VIVADO_STAMP)
	@test -f "$(XSA)" || { echo "ERROR: XSA is missing; run 'make clean vivado_prj'"; exit 1; }
	@test -f "$(BIT)" || { echo "ERROR: BIT is missing; run 'make clean vivado_prj'"; exit 1; }

vitis_prj: $(ELF)

# A completion marker represents the XSA and BIT generated by one invocation.
$(VIVADO_STAMP): $(VIVADO_TCL) $(VIVADO_SRCS)
	@echo "==> Building Vivado project"
	@mkdir -p "$(BUILD_DIR)" "$(LOG_DIR)"
	$(VIVADO) -mode batch -notrace -source "$(VIVADO_TCL)" \
		-log "$(LOG_DIR)/vivado_prj.log" \
		-journal "$(LOG_DIR)/vivado_prj.jou" \
		-tclargs "$(VIVADO_SRC_DIR)" "$(VIVADO_PRJ_DIR)" "$(XSA)" "$(BIT)" "$(JOBS)"
	@test -f "$(XSA)" || { echo "ERROR: XSA was not generated: $(XSA)"; exit 1; }
	@test -f "$(BIT)" || { echo "ERROR: BIT was not generated: $(BIT)"; exit 1; }
	@touch "$@"

$(XSA) $(BIT): $(VIVADO_STAMP)
	@test -f "$@" || { echo "ERROR: Missing Vivado artifact: $@"; exit 1; }

$(ELF): $(VITIS_TCL) $(VITIS_SRCS) $(VIVADO_STAMP)
	@echo "==> Building Vitis project"
	@mkdir -p "$(BUILD_DIR)" "$(LOG_DIR)"
	$(XSCT) "$(VITIS_TCL)" "$(XSA)" "$(VITIS_SRC_DIR)" "$(VITIS_PRJ_DIR)" "$(ELF)"
	@test -f "$(ELF)" || { echo "ERROR: ELF was not generated: $(ELF)"; exit 1; }

# =====================================================
# Utility targets
# =====================================================
clean:
	@echo "==> Removing generated projects, artifacts, and logs"
	@rm -rf "$(BUILD_DIR)" "$(LOG_DIR)" \
		"$(SRC_DIR)/mb_baiyang_tinyphy_release.gen" \
		"$(SRC_DIR)/shell_s2c_vu19p_s2c_vu19p.gen" \
		.Xil vivado.log vivado.jou


